# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-24 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game2_group', to='otree.Session')),
            ],
            options={
                'db_table': 'game2_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('game2_score', otree.db.models.IntegerField(null=True)),
                ('game2_rank', otree.db.models.IntegerField(null=True)),
                ('game2_bonus', otree.db.models.IntegerField(null=True)),
                ('attempted', otree.db.models.IntegerField(null=True)),
                ('firm', otree.db.models.StringField(max_length=10000, null=True)),
                ('time_Instructions2', otree.db.models.StringField(max_length=10000, null=True)),
                ('time_Game2', otree.db.models.StringField(max_length=10000, null=True)),
                ('time_Results2', otree.db.models.StringField(max_length=10000, null=True)),
                ('time_Results', otree.db.models.StringField(max_length=10000, null=True)),
                ('time_Survey7', otree.db.models.StringField(max_length=10000, null=True)),
                ('time_Survey8', otree.db.models.StringField(max_length=10000, null=True)),
                ('time_Survey10', otree.db.models.StringField(max_length=10000, null=True)),
                ('time_Survey12', otree.db.models.StringField(max_length=10000, null=True)),
                ('q7_choice', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='You chose Firm A/B in the first contest.         If given the choice again would you still choose Firm A/B or would you change your choice?')),
                ('q7', otree.db.models.LongStringField(null=True, verbose_name='Why?')),
                ('q8', otree.db.models.StringField(choices=[('Won', 'Won'), ('Came Second', 'Came Second'), ('Lost', 'Lost')], max_length=10000, null=True, verbose_name='Do you think you won, came second, or lost the first contest?')),
                ('q9', otree.db.models.StringField(choices=[('Won', 'Won'), ('Came Second', 'Came Second'), ('Lost', 'Lost')], max_length=10000, null=True, verbose_name='Do you think you won, came second, or lost the second contest?')),
                ('q10', otree.db.models.PositiveIntegerField(null=True, verbose_name='Age')),
                ('q11', otree.db.models.StringField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Non-binary', 'Non-binary'), ('Other', 'Other')], max_length=10000, null=True, verbose_name='Gender')),
                ('q12', otree.db.models.LongStringField(null=True, verbose_name='Was there any part of the study that was confusing? Please help us improve our study by providing feedback.')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game2.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game2_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game2_player', to='otree.Session')),
            ],
            options={
                'db_table': 'game2_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game2_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'game2_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game2.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game2.Subsession'),
        ),
    ]
